[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
base-goerli = "https://goerli.base.org"
sepolia = "https://eth-sepolia.public.blastapi.io"
base = "https://mainnet.base.org"

[etherscan]
base-goerli = { key = "${BASESCAN_API_KEY}", chain = "base-goerli" }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = "sepolia" }
base = { key = "${BASESCAN_API_KEY}", chain = "base" }
